name: Continuous Integration

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "pypy-2.7", "pypy-3.6"]
        lua-version: ["bundle", "lua5.2", "lua5.3", "luajit-5.1"]

        exclude:
          - os: windows-2019
            lua-version: lua5.2
          - os: windows-2019
            lua-version: lua5.3
          - os: windows-2019
            lua-version: luajit-5.1

    steps:
    - uses: actions/checkout@v2

    - name: Check out recursively
      run: git submodule update --init --recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Python packages
      run: python -m pip install -U "pip<21" "setuptools<45" wheel && python -m pip install -U tox virtualenv

    - name: Set up Lua ${{ matrix.lua-version }}
      if: ${{ !contains(matrix.lua-version, 'bundle') }}
      run: sudo apt-get install lib${{ matrix.lua-version }}-dev

    - name: Build wheel
      run: python -m pip install -r requirements.txt && python setup.py sdist bdist_wheel
      env:
        SETUP_OPTIONS: ${{ !contains(matrix.lua-version, 'luajit') && (contains(matrix.lua-version, 'bundle') && '--use-bundle' || '--no-luajit') || '' }}
        CFLAGS: ${{ contains(matrix.lua-version, 'bundle') && '-flto -g' || '-g' }}
        LDFLAGS: ${{ contains(matrix.lua-version, 'bundle') && '-flto' || '' }}

    - name: Run tests with tox
      run: tox -e py # Runs the version of Python tox is currently using
      continue-on-error: ${{ contains(matrix.python-version, 'pypy') }}
      env:
        SETUP_OPTIONS: ${{ !contains(matrix.lua-version, 'luajit') && (contains(matrix.lua-version, 'bundle') && '--use-bundle' || '--no-luajit') || '' }}
        CFLAGS: ${{ contains(matrix.lua-version, 'bundle') && '-flto -g' || '-g' }}
        LDFLAGS: ${{ contains(matrix.lua-version, 'bundle') && '-flto' || '' }}

    - name: Upload wheels
      if: ${{ contains(matrix.lua-version, 'bundle') }}
      uses: actions/upload-artifact@v2
      with:
        name: wheels-${{ matrix.os }}
        path: dist/*.whl
        if-no-files-found: ignore
